# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doxwiki', '0002_auto_20161204_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_set', to='doxwiki.Category'),
        ),
    ]
