# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doxwiki', '0003_auto_20161204_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=300, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='categories',
            field=models.ManyToManyField(blank=True, to='doxwiki.Category'),
        ),
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(blank=True, to='doxwiki.Tag'),
        ),
    ]
