# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doxwiki', '0005_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doxwiki.Page'),
        ),
    ]
